imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
          point: CTF\CommonBundle\DBAL\PointType
        mapping_types:
          enum: string
          point: point

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
          default:
            auto_mapping: true
            dql:
              numeric_functions:
                DISTANCE: CTF\CommonBundle\DBAL\Distance
                POINT_STR: CTF\CommonBundle\DBAL\PointStr

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
  db_driver: orm
  firewall_name: secured_area
  user_class: CTF\UserBundle\Entity\User

hwi_oauth:
  firewall_name: secured_area
  fosub:
    username_iterations: 30
    properties:
      facebook: facebook_id
      google: google_id
  connect:
    account_connector: ctf_user_provider
  resource_owners:
    facebook:
      type: facebook
      client_id: "447681865324434"
      client_secret: "60becc1be2a92474fbea8f23a45a64cf"
      scope: ""
    
    google:
      type: google
      client_id: "1002924713144.apps.googleusercontent.com"
      client_secret: "wHvy_CTW2XYU_uXhc-o3dfVH"
      scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
#
    #twitter:
    #  type: twitter
    #  client_id: ~
    #  client_secret: ~

fos_js_routing:
    routes_to_expose: ctf_quest_homepage