#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

ctf_quest:
    resource: "@CTFQuestBundle/Resources/config/routing.yml"
    prefix:   /

ctf_security:
    resource: "@CTFSecurityBundle/Resources/config/routing.yml"
    prefix:   /

ctf_user:
    resource: "@CTFUserBundle/Resources/config/routing.yml"
    prefix:   /

ctf_common:
    resource: "@CTFCommonBundle/Resources/config/routing.yml"
    prefix:   /

ctf_login:
    resource: "@CTFLoginBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#login:
#  pattern: /quest/login
#  defaults: { _controller: CTFSecurityBundle:Security:login }
  
#login_check:
#  pattern: /quest/login_check
  
#logout:
#  pattern: /quest/logout

#facebook_login:
#  pattern: /quest/login/facebook

#gplus_login:
#  pattern: /quest/login/google

#twitter_login:
#  pattern: /quest/login/twitter
