jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_user:
          id: fos_user.user_provider.username_email
          #entity: { class: CTFUserBundle:User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        #login_firewall:
        #  pattern: ^/login$
        #  anonymous: ~
          
        secured_area:
          pattern: ^/
          form_login:
            provider: fos_user
            csrf_provider: form.csrf_provider
          logout: true
          anonymous: true
        #  pattern: ^/quest
        #  anonymous: ~
        #  oauth:
        #    resource_owners:
        #      fb: "/quest/login/facebook"
        #      gplus: "/quest/login/google"
        #     #twitter: "/quest/login/twitter"
        #    login_path: "/quest/login"
        #    failure_path: "/quest/login"
        #    oauth_user_provider:
        #      service: ctf_user.entity.user
        #  form_login:
        #    provider: users
        #    login_path: /quest/login
        #    check_path: /quest/login_check
        #    default_target_path: /quest
        #  logout:
        #    path: /quest/logout
        #    target: /
        #  remember_me:
        #    key: "%secret%"
        #    lifetime: 604800
        #    path: /
        #    domain: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/quest/, role: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
