ctf_admin_homepage:
    pattern:  /admin
    defaults: { _controller: CTFAdminBundle:Admin:index }
    
ctf_admin_settings:
    pattern: /admin/settings
    defaults: { _controller: CTFAdminBundle:Admin:settings }

ctf_admin_announce:
    pattern: /admin/announce
    defaults: { _controller: CTFAdminBundle:Admin:announce }
    options:
      expose: true

ctf_admin_team_count:
    pattern: /admin/teams/count
    defaults: { _controller: CTFAdminBundle:Admin:teamCount }
    options:
      expose: true

ctf_admin_genders_count:
    pattern: /admin/gender/count
    defaults: { _controller: CTFAdminBundle:Admin:gendersCount }
    options:
      expose: true

ctf_admin_chat:
    pattern: /admin/chat
    defaults: { _controller: CTFAdminBundle:Admin:chat }

ctf_admin_stage:
    pattern: /admin/stage
    defaults: { _controller: CTFAdminBundle:Admin:stage }

ctf_admin_stage_form:
    pattern: /admin/stage/form/{id}
    defaults: { _controller: CTFAdminBundle:Admin:stageForm, id: -1 }
    options:
      expose: true
      
ctf_admin_stage_list:
    pattern: /admin/stage/list/{q}
    defaults: { _controller: CTFAdminBundle:Admin:stageList, q: 0 }
    options:
      expose: true

ctf_admin_stage_question:
    pattern: /admin/stage/question/{id}
    defaults: { _controller: CTFAdminBundle:Admin:question, id: -1 }
    options:
      expose: true