ctf_user_edit_profile:
    pattern:  /profile/edit
    defaults: { _controller: CTFUserBundle:User:editProfile }

ctf_get_edit_form:
    pattern: /profile/edit/form
    defaults: { _controller: CTFUserBundle:User:grabForm }
    options:
        expose: true