parameters:
#    ctf_user.example.class: CTF\UserBundle\Example

services:
#    ctf_user.example:
#        class: %ctf_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

  ctf_user.entity.user:
    class: CTF\UserBundle\Entity\User