parameters:
#    ctf_team.example.class: CTF\TeamBundle\Example

services:
#    ctf_team.example:
#        class: %ctf_team.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ctf.form.select_team:
        class: "CTF\TeamBundle\Form\TeamSelectType"
        arguments: [@ctf.form.select_team_listener]
        tags:
          - { name: form.type, alias: select_team }
    
    ctf.form.select_team_listener:
        class: "CTF\TeamBundle\Form\Event\TeamSelectListener"
        arguments: [@form.factory]