parameters:
#    ctf_login.example.class: CTF\LoginBundle\Example

services:
#    ctf_login.example:
#        class: %ctf_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
