GlobalState:
    type: entity
    table: global_state
    fields:
        enableCtf:
            id: true
            type: boolean
            nullable: false
            column: enable_ctf
        enableChat:
            id: true
            type: boolean
            nullable: false
            column: enable_chat
    lifecycleCallbacks: {  }
