Organization:
    type: entity
    table: organization
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
