Stages:
    type: entity
    table: stages
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: text
            nullable: false
        description:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
