Team:
    type: entity
    table: team
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 30
            fixed: false
            nullable: false
        status:
            type: text
            nullable: true
        score:
            type: integer
            unsigned: false
            nullable: false
        teamPic:
            type: text
            nullable: true
            column: team_pic
    manyToMany:
        user:
            targetEntity: AuthUsers
            cascade: {  }
            mappedBy: null
            inversedBy: team
            joinTable:
                name: team_members
                joinColumns:
                    -
                        name: team_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
