upload:
    pattern: /upload
    defaults: { _controller: CTFCommonBundle:Upload:upload }

ctf_fb_channel:
    pattern: /fb/channel
    defaults: { _controller: CTFChannelBundle:Channel:facebookChannel }
    options:
      expose: true