AuthUsers:
    type: entity
    table: auth_users
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 255
            fixed: false
            nullable: false
        usernameCanonical:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: username_canonical
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        emailCanonical:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            length: 32
            fixed: false
            nullable: false
        password:
            type: string
            length: 255
            fixed: false
            nullable: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: false
        expired:
            type: boolean
            nullable: false
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
        credentialsExpired:
            type: boolean
            nullable: false
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
        googleId:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: google_id
        googleAccessToken:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: google_access_token
        facebookId:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: facebook_id
        facebookAccessToken:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: facebook_access_token
        twitterId:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: twitter_id
        twitterAccessToken:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: twitter_access_token
        fname:
            type: string
            length: 50
            fixed: false
            nullable: true
        lname:
            type: string
            length: 50
            fixed: false
            nullable: true
        dp:
            type: blob
            nullable: true
        dob:
            type: date
            nullable: true
        aboutMe:
            type: text
            nullable: true
            column: about_me
        gender:
            type: string
            length: null
            fixed: false
            nullable: true
        phone:
            type: string
            length: 30
            fixed: false
            nullable: true
        city:
            type: string
            length: 30
            fixed: false
            nullable: true
        website:
            type: text
            nullable: true
        location:
            type: point
            nullable: true
        loginMode:
            type: string
            length: null
            fixed: false
            nullable: false
            column: login_mode
    manyToOne:
        org:
            targetEntity: Organization
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                org_id:
                    referencedColumnName: id
            orphanRemoval: false
        state:
            targetEntity: Zone
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                state_id:
                    referencedColumnName: zone_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
