Countries:
    type: entity
    table: countries
    fields:
        countryId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: country_id
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 60
            fixed: false
            nullable: false
        isoCode2:
            type: text
            nullable: true
            column: iso_code_2
        isoCode3:
            type: text
            nullable: true
            column: iso_code_3
        postCodeRequired:
            type: boolean
            nullable: false
            column: post_code_required
    lifecycleCallbacks: {  }
