Questions:
    type: entity
    table: questions
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: text
            nullable: false
        content:
            type: text
            nullable: false
        answerTpl:
            type: text
            nullable: false
            column: answer_tpl
        hints:
            type: text
            nullable: false
    manyToMany:
        stage:
            targetEntity: Stages
            cascade: {  }
            mappedBy: question
            inversedBy: null
            joinTable: null
            orderBy: null
        quest:
            targetEntity: UserQuest
            cascade: {  }
            mappedBy: question
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
