Users:
    type: entity
    table: users
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        fname:
            type: string
            length: 50
            fixed: false
            nullable: false
        lname:
            type: string
            length: 50
            fixed: false
            nullable: false
        screenName:
            type: string
            length: 30
            fixed: false
            nullable: true
            column: screen_name
        email:
            type: string
            length: 200
            fixed: false
            nullable: false
        password:
            type: blob
            nullable: false
        dp:
            type: blob
            nullable: true
        aboutMe:
            type: text
            nullable: true
            column: about_me
        dob:
            type: date
            nullable: true
        gender:
            type: string
            length: null
            fixed: false
            nullable: true
        phone:
            type: string
            length: 14
            fixed: false
            nullable: false
        state:
            type: string
            length: 25
            fixed: false
            nullable: false
        city:
            type: string
            length: 30
            fixed: false
            nullable: false
        website:
            type: text
            nullable: true
        location:
            type: point
            nullable: true
        smsVerify:
            type: boolean
            nullable: true
            column: sms_verify
        loginMode:
            type: string
            length: null
            fixed: false
            nullable: true
            column: login_mode
        isBanned:
            type: boolean
            nullable: true
            column: is_banned
        updatedTstamp:
            type: datetime
            nullable: false
            column: updated_tstamp
        createdTstamp:
            type: datetime
            nullable: false
            column: created_tstamp
    manyToMany:
        team:
            targetEntity: Team
            cascade: {  }
            mappedBy: user
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        org:
            targetEntity: Organization
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                org_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
