# Routing for the certificate module
ctf_certificate_test:
    pattern: /certify/me/{mode}
    defaults: { _controller: "CTFCertificateBundle:Certificate:index", mode: "png" }

ctf_certificate_user:
    pattern: /certify/user/{id}
    defaults: { _controller: "CTFCertificateBundle:Certificate:user" }